import React, {useEffect, useState} from 'react'
import Head from 'next/head'
import Layout from '../components/layout/layout'
import '../styles/globals.css'
import '../styles/style.css'

function MyApp({ Component, pageProps }) {
  const [mobileDevice, setMobileDevice] = useState(false);
  const [desktopDevice, setDesktopDevice] = useState(false);

  useEffect(() => {
      const mobile = window.matchMedia('(max-width: 768px)')
      if (mobile.matches) {
        mobile.addEventListener('change', () =>{})
        setMobileDevice(true);
      } else {
        setDesktopDevice(true);
      }
  }, [mobileDevice, desktopDevice])

  return (
    <>
      <Head>
        <title>Rucher Frisson</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout
        desktopDevice={desktopDevice}
        mobileDevice={mobileDevice}
      >
        <Component
          desktopDevice={desktopDevice}
          mobileDevice={mobileDevice}
          {...pageProps}
        />
      </Layout>
    </>
  )
}

export default MyApp
